import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

import { cn } from '@/lib/utils';

import { QueryProvider } from '../providers/QueryProvider';

const sans = Poppins({
  variable: '--font-sans',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn('antialiased min-h-dvh', sans.className)}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
